vast_pipeline/urls.py
"""
This module contains the urls used by the Django web server.
"""

from django.urls import include, path, re_path, register_converter
from rest_framework.routers import DefaultRouter
import tagulous.views

from vast_pipeline import views, converters
from vast_pipeline.models import Source


app_name = 'vast_pipeline'
register_converter(converters.RightAscensionConverter, "ra")
register_converter(converters.DeclinationConverter, "dec")
register_converter(converters.AngleConverter, "angle")

router = DefaultRouter()
router.register(r'piperuns', views.RunViewSet, 'api_pipe_runs')
router.register(r'images', views.ImageViewSet, 'api_images')
router.register(r'measurements', views.MeasurementViewSet, 'api_measurements')
router.register(r'sources', views.SourceViewSet, 'api_sources')
router.register(r'rawimages', views.RawImageListSet, 'api_rawimages')
router.register(r'runcfg', views.RunConfigSet, 'api_runcfg')
router.register(r'runlog', views.RunLogSet, 'api_runlog')
router.register(r'sourcesfavs', views.SourceFavViewSet, 'api_sources_favs')
router.register(r'utils', views.UtilitiesSet, 'api_utils')
router.register(r'plots', views.SourcePlotsSet, 'api_source_plots')

urlpatterns = [
    path('piperuns/', views.RunIndex, name='run_index'),
    path('piperuns/<int:id>/', views.RunDetail, name='run_detail'),
    path('images/', views.ImageIndex, name='image_index'),
    re_path(
        r'^images/(?P<id>\d+)(?:/(?P<action>[\w]+))?/$',
        views.ImageDetail,
        name='image_detail'
    ),
    path('measurements/', views.MeasurementIndex, name='measurement_index'),
    re_path(
        r'^measurements/(?P<id>\d+)(?:/(?P<action>[\w]+))?/$',
        views.MeasurementDetail,
        name='measurement_detail'
    ),
    path('sources/query/', views.SourceQuery, name='source_query'),
    path('sources/query/plot/', views.SourceEtaVPlot, name='source_etav_plot'),
    path('sources/query/plot/update/<int:pk>/', views.SourceEtaVPlotUpdate, name='source_etav_plot_update'),
    path('sources/<int:pk>/', views.SourceDetail, name='source_detail'),
    path('sources/favs/', views.UserSourceFavsList, name='source_favs'),
    path(
        "sources/tags/autocomplete/",
        tagulous.views.autocomplete_login,
        kwargs={"tag_model": Source.tags.tag_model},
        name="source_tags_autocomplete",
    ),
    path('cutout/<int:measurement_id>/', views.ImageCutout.as_view(), name='cutout'),
    path('cutout/<int:measurement_id>/<str:size>/', views.ImageCutout.as_view(), name='cutout'),
    path(
        'measurements/<int:image_id>/<ra:ra_deg>,<dec:dec_deg>,<angle:radius_deg>/region/',
        views.MeasurementQuery.as_view(),
        name="measurements_region"
    ),
    path('api/', include(router.urls)),
]

webinterface/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from vast_pipeline.views import Home, Login


urlpatterns = [
    path('pipe-admin/', admin.site.urls),
    path('', Home, name='index'),
    path('login/', Login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('vast_pipeline.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

# enable debug toolbar in developement
if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

# for production to change the base URL (e.g. server has other apps, like
# jupyter hub running)
if settings.BASE_URL and settings.BASE_URL != '':
    admin.site.site_url = '/' + settings.BASE_URL.strip('/') + '/'
    urlpatterns = [
        path(settings.BASE_URL.strip('/') + '/', include(urlpatterns))
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="VAST Pipeline WebApp for processing the images from the ASKAP Telescope and detecting transient sources">
  <meta name="author" content="VAST Developement Team">

  {% block title %}
  <title>VAST Pipeline</title>
  {% endblock title %}

  <!-- VAST icon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Stylesheet. Includes Bootstrap, sb-admin-2, and custom styles -->
  <link href="{% static 'css/pipeline.min.css' %}" rel="stylesheet">

  {% block head %}

  {% endblock head %}

</head>

<body id="page-top">
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}" id='homeLogo'>
        <img src="{% static 'img/vast.png' %}" width="50%" >
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      {% if user.is_staff %}
      <!-- Nav Item - Admin Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdmin" aria-expanded="true" aria-controls="collapseAdmin">
          <i class="fas fa-fw fa-cog"></i>
          <span>Admin</span>
        </a>
        <div id="collapseAdmin" class="collapse" aria-labelledby="headingDataset" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'admin:index' %}">Django</a>
          </div>
        </div>
      </li>
      {% endif %}

      <!-- Nav Item - Pipeline Runs -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'vast_pipeline:run_index' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Pipeline Runs</span>
        </a>
      </li>

      <!-- Nav Item - Sources -->
      <li class="nav-item" id="sourcesLink">
        <a class="nav-link collapsed" href="{% url 'vast_pipeline:source_query' %}">
          <i class="fas fa-fw fa-share-alt"></i>
          <span>Sources Query</span>
        </a>
      </li>

      <!-- Nav Item - Images -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'vast_pipeline:image_index' %}">
          <i class="fas fa-fw fa-images"></i>
          <span>Images</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" target="_blank" href="https://vast-survey.org/vast-pipeline/">
          <i class="fas fa-file-alt"></i>
          <span>Pipeline Documentation</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" target="_blank" href="https://github.com/askap-vast/vast-pipeline/issues/new">
          <i class="fab fa-fw fa-github"></i>
          <span>Pipeline Repository</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" target="_blank" href="https://github.com/askap-vast/vast-pipeline/issues/new">
          <i class="fas fa-fw fa-exclamation"></i>
          <span>Raise Issue</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" target="_blank" href="https://github.com/askap-vast/vast-pipeline/discussions/new">
          <i class="far fa-comments"></i>
          <span>Start a Discussion</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLinks" aria-expanded="true" aria-controls="collapseLinks">
          <i class="fas fa-fw fa-link"></i>
          <span>VAST Links</span>
        </a>
        <div id="collapseLinks" class="collapse" aria-labelledby="headingDataset" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" target="_blank" href="https://github.com/askap-vast">GitHub</a>
            <a class="collapse-item" target="_blank" href="https://hub.vast-survey.org/>JupyterHub</a>
            <a class="collapse-item" target="_blank" href="https://vast-survey.org">Website</a>
            <a class="collapse-item" target="_blank" href="https://github.com/askap-vast/vast-project/wiki">Wiki</a>
          </div>
        </div>
      </li>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        {% if maintainance_message %}
        <div id="maintainanceMessage" class="text-gray-900 text-center">
          <strong class="text-lg">MAINTAINER MESSAGE: </strong>{{ maintainance_message }}
        </div>
        {% endif %}

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'index' %}">Home</a>
            </li>

            {% block breadcrumb %}

            {% endblock breadcrumb %}

            <li class="breadcrumb-item active">Overview</li>
          </ol>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                  {% if user.first_name %}
                  {{ user.first_name }}
                  {% else %}
                  {{ user.username }}
                  {% endif %}
                </span>
                {% for ass in backends.associated %}
                  {% if ass.provider == 'github-org' %}
                    {% if 'avatar_url' in ass.extra_data %}
                    <img class="img-profile rounded-circle" src="{{ ass.extra_data.avatar_url }}" alt="">
                    {% else %}
                    <img class="img-profile rounded-circle" src="{% static 'img/user-32.png' %}" width="32" height="32" alt="">
                    {% endif %}
                  {% endif %}

                {% endfor %}
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'vast_pipeline:source_favs' %}">
                  <i class="fas fa-star fa-sm fa-fw mr-2 text-gray-400"></i>
                  Favourite Sources
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>

        {% block content %}

        {% endblock content %}

        {% block messages %}
          <ul class="messages" id="messages-list">
            {% include 'messages.html' %}
          </ul>
        {% endblock messages %}

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>VAST Pipeline version {% if pipeline_version_url %}<a href={{ pipeline_version_url }}>{% endif %}{{ pipeline_version }}{% if pipeline_version_url %}</a>{% endif %}. Copyright &copy; VAST Development Team 2020 - All rights reserved.</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  {% block modal %}
  {% endblock modal %}

  {% block scripts %}
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'vendor/startbootstrap-sb-admin-2/sb-admin-2.min.js' %}"></script>

  <!-- Toasts script for all pages-->
  <script src="{% static 'js/toasts.min.js' %}"></script>
  {% endblock scripts %}

  {% block custom_page_scripts %}
  {% endblock custom_page_scripts %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}


{% block head %}

<link rel='stylesheet' href="{% static 'css/celestial.min.css' %}" />

{% endblock head %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    {% if user.is_authenticated %}
      <h1 class="h3 mb-4 text-gray-800">Welcome back {{ user.first_name }}!</h1>
    {% else %}
      <h1 class="h3 mb-4 text-gray-800">Welcome back!</h1>
    {% endif %}
    <div>
      VAST Pipeline version {% if pipeline_version_url %}<a href={{ pipeline_version_url }}>{% endif %}{{ pipeline_version }}{% if pipeline_version_url %}</a>{% endif %}.
    </div>
    <a href="https://github.com/askap-vast/vast-pipeline" target="_blank" class="btn btn-sm btn-secondary btn-icon-split shadow-sm">
      <span class="icon text-white-600">
        <i class="fab fa-github fa-lg"></i>
      </span>
      <span class="text">Contribute on GitHub</span>
    </a>
  </div>

  <div class="row">

    <!-- Nr Piperuns -->
    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text font-weight-bold text-success mb-1">Go to Pipeline Runs</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-bookmark fa-2x text-gray-300"></i>
              </div>
            </div>
            <a href="{% url 'vast_pipeline:run_index' %}" class="stretched-link"></a>
          </div>
        </div>
    </div>

    <!-- Nr Sources -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text font-weight-bold text-warning mb-1">Go to Source Query</div>
            </div>
            <div class="col-auto">
              <i class="fas fa-share-alt fa-2x text-gray-300"></i>
            </div>
          </div>
          <a href="{% url 'vast_pipeline:source_query' %}" class="stretched-link"></a>
        </div>
      </div>
    </div>

    <!-- Nr Images -->
    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text font-weight-bold text-primary mb-1">Go to Images</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-images fa-2x text-gray-300"></i>
              </div>
            </div>
            <a href="{% url 'vast_pipeline:image_index' %}" class="stretched-link"></a>
          </div>
        </div>
    </div>

  </div>

  <div class="row">
    <div class="col-lg-12">
      <!-- Change Log card -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Welcome to the VAST Pipeline!</h6>
        </div>
        <div class="card-body overflow-auto">
         <p>Use the navigation sidebar to explore the website. Where to go for common tasks:</p>
          <ul>
            <li>To search for a source by name or coordinates use the <a href="{% url 'vast_pipeline:source_query' %}">Sources Query</a> page.</li><br>
            <li>To see what pipeline runs are available or to initialise and launch a run see the <a href="{% url 'vast_pipeline:run_index' %}">Pipeline Runs</a> page.</li><br>
          </ul>
        <p>If you find an issue please <a target="_blank" href="https://github.com/askap-vast/vast-pipeline/issues/new">raise an issue on Github</a>. This link is always available via the sidebar. For ideas or features that require more discussion, or to ask a general question about the pipeline, there is also a link to <a target="_blank" href="https://github.com/askap-vast/vast-pipeline/discussions/new/">start a discussion on Github</a>.</p>
        <p>Links to other VAST servies such as the <a target="_blank" href="https://data.vast-survey.org">JupyterHub</a> or <a target="_blank" href="https://github.com/askap-vast/vast-project/wiki">Wiki</a> can be found under 'VAST Links' in the sidebar.</p>
        <p>Full pipeline documentation is available on the <a target="_blank" href="https://vast-survey.org/vast-pipeline/">documentation website</a>.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->

{% endblock content %}

templates/sources_etav_plot.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% load unit_tags %}

{% block head %}

<link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" />
<link rel="stylesheet" href="{% static 'vendor/datatables-buttons/buttons.bootstrap4.min.css' %}" />

{% endblock head %}


{% block breadcrumb %}

<li class="breadcrumb-item">
  <a href="{% url 'vast_pipeline:source_query' %}">Sources</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'vast_pipeline:source_etav_plot' %}">Query &eta;-V Plot</a>
</li>

{% endblock breadcrumb %}

{% block content %}
<!-- Begin Page Content -->

<div class="container-fluid flex-column">

  <div class="row">
    <div class="col-xl-5 mb-4">

      <!-- Eta V Plot -->
      <div class="card shadow h-100">
        <div class="card-header py-3 clearfix" id="etavplotHeader">
          <h6 class="m-0 font-weight-bold text-primary float-left">&eta;-V Plot</h6>
        </div>
        <div class="card-body">
          <div id="etaVBokeh">
            {% if plot_ok == 0 %}
              <center>Error.</center>
            {% endif %}
          </div>

        </div>
      </div>
    </div>

    <div class="col-xl-7 mb-4">
      <div class="row">
        <div class="col mb-4">
          <div class="card shadow h-100">
            <div class="card-header py-3 clearfix" id="lightcurveHeader">
              <h6 class="m-0 font-weight-bold text-primary float-left">Selected Source Light Curve</h6>
            </div>
            <div class="card-body">
              <div id="lightCurveBokeh"></div>
            </div>
          </div>
        </div>
      </div>

      <div id='cardsUpdate'>
        {% include 'sources_etav_plot_update.html' %}
      </div>

    </div>
  </div>

  <div style="position: fixed; top: 0; right: 0; z-index: 99">
    <div id="alert_placeholder"></div>
  </div>

</div> <!-- /.container-fluid -->

{% endblock content %}

{% block scripts %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
 <script src="{% static 'vendor/startbootstrap-sb-admin-2/sb-admin-2.min.js' %}"></script>

<!-- Toasts script -->
<script src="{% static 'js/toasts.min.js' %}"></script>
{% endblock scripts %}


{% block custom_page_scripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'vendor/datatables-buttons/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'vendor/datatables-buttons/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'vendor/datatables-buttons/buttons.colVis.min.js' %}"></script>
<script src="{% static 'vendor/datatables-buttons/buttons.html5.min.js' %}"></script>
<script src="{% static 'vendor/datatables-buttons/buttons.flash.min.js' %}"></script>
<script src="{% static 'vendor/jszip/jszip.min.js' %}"></script>

<!-- Datatable scripts -->
<script src="{% static 'js/datatables-pipeline.min.js' %}"></script>

<!-- Bokeh scripts -->
<script src="{% static 'vendor/bokehjs/bokeh.min.js' %}"></script>
<script src="{% static 'vendor/bokehjs/bokeh-widgets.min.js' %}"></script>

<script src="{% static 'js/clipboard-copy.min.js' %}"></script>
<script src="{% static 'js/source-fav.min.js' %}" apiSourceFavUrl="{% url 'vast_pipeline:api_sources_favs-list' %}" id="SourceFavScript"></script>

<script type="text/javascript">
  function getEtaVPlot(eta_sigma = 3.0, v_sigma = 3.0, fluxType = "peak") {
    let usePeakFlux = fluxType === "peak";
    fetch("{% url 'vast_pipeline:api_source_plots-etavplot' %}?eta_sigma=" + eta_sigma + "&v_sigma=" + v_sigma + "&peak_flux=" + usePeakFlux)
      .then(function (response) {
        return response.json()
      })
      .then(function (item) {
        $("#etaVBokeh").empty();
        return Bokeh.embed.embed_item(item, "etaVBokeh")
      })
  }

  function getLightcurvePlot(id, fluxType = "peak") {
    let usePeakFlux = fluxType === "peak";
    fetch("{% url 'vast_pipeline:api_source_plots-lightcurve' -99 %}?peak_flux=".replace('-99', id) + usePeakFlux)
      .then(function (response) {
        return response.json()
      })
      .then(function (item) {
        $("#lightCurveBokeh").empty();
        return Bokeh.embed.embed_item(item, "lightCurveBokeh")
      })
  }

  $(document).ready(function () {
    var plot_ok = {{ plot_ok }};
    if (plot_ok == true){
      getEtaVPlot(3.0, 3.0, 'peak');
    }
  });

  function update_card(id) {
    $('#cardsUpdate').html('').load(
      "{% url 'vast_pipeline:source_etav_plot_update' 0 %}".replace('0', id),
      function() {
        // redraw the external results table, function is defined in datatables-pipeline.js
        drawExternalResultsTable('#externalResultsTable');
      }
    ); // <--- this code instead of $.ajax(lala)
  }
</script>

{% endblock custom_page_scripts %}

templates/sources_etav_plot_update.html
{% load unit_tags %}

<div class="row">
  <div class="col mb-4">
    <div id="sourceInfoCard">
      <div class="card shadow h-100">
        <div class="card-header py-3 clearfix" id="sourceInfoHeader">
          <h6 class="m-0 font-weight-bold text-primary float-left">Source Information</h6>
        </div>
        <div class="card-body">
          {% if source %}
          <div class="float-left">
            <strong>{{ source.name }}</strong>
          </div>
          <div class="float-right">
            {% include 'source_fav_button.html' %}
            <a href="{% url 'vast_pipeline:source_detail' source.id %}"
              class="d-none d-sm-inline-block btn btn-sm btn-primary btn-icon-split shadow-sm" target="_blank"
              title="Go to the source summary page.">
              <span class="text">Source detail page</span>
              <span class="icon text-white-600">
                <i class="fa fa-arrow-right fa-sm"></i>
              </span>
            </a>
          </div>
          <br>
          <strong>Position: </strong><span class="clipboard-copy">{{ source.wavg_ra_hms }} {{ source.wavg_dec_dms }}</span><br>
          <strong>Position (Decimal): </strong><span class="clipboard-copy">{{ source.wavg_ra|floatformat:6 }} {{ source.wavg_dec|floatformat:6 }}</span><br>
          <strong>Position (Galactic): </strong><span class="clipboard-copy">{{ source.wavg_l|floatformat:6 }} {{ source.wavg_b|floatformat:6 }}</span>
          <div class="row">
            <div class="col">
              <strong>Avg. Compactness: </strong>{{ source.avg_compactness|floatformat:3 }}
            </div>
            <div class="col">
              <strong>Neighbour Dist: </strong>{{ source.n_neighbour_dist|deg_to_arcmin|floatformat:2 }}&prime;
            </div>
            <div class="col">
              <strong>Max SNR: </strong>{{ source.max_snr|floatformat:2 }}
            </div>
            <div class="col">
              <strong>Min SNR: </strong>{{ source.min_snr|floatformat:2 }}
            </div>
          </div>
          <div class="row">
            <div class="col">
            <strong>Nr Relations: </strong>{{ source.n_rel }}
            </div>
            <div class="col">
            <strong>Nr Siblings: </strong>{{ source.n_sibl }}
            </div>
            <div class="col">
            <strong>New Source: </strong>{{ source.new }}
            </div>
            <div class="col">
            <strong>New High Sigma:</strong>{% if source.new %}{{ source.new_high_sigma|floatformat:2 }}{% else %}N/A{% endif %}
            </div>
          </div>
          {{ datatables|json_script:"datatable-conf" }}
          {% else %}
          The details of a selected source will appear here.
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col mb-4">
    <div class="card shadow mb-4 h-100">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">External Search Results (1 arcmin)</h6>
      </div>
      <div class="card-body small">
        <div class="table-responsive">
          {% if source %}
          <table class="table table-sm table-bordered table-striped table-hover" id="externalResultsTable"
            width="100%" cellspacing="0" data-server-side="false"
            data-ajax="{% url 'vast_pipeline:api_utils-external-search' %}?coord={{ source.wavg_ra_hms }}{{ source.wavg_dec_dms }}&format=datatables&keep=otype_long,database">
            <thead>
              <tr>
                <th data-data="object_name">ID</th>
                <th data-data="separation_arcsec">Dist (arcsec)</th>
                <th data-data="otype">Type</th>
                <th data-data="ra_hms">RA (hms)</th>
                <th data-data="dec_dms">Dec (dms)</th>
              </tr>
            </thead>
          </table>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'source_fav_modal.html' %}